cargo-features = ["edition2021"]

[package]
name = "raft-kv-rs"
version = "0.1.0"
authors = ["Harikrishnan Prabakaran <Harikrishnan.Prabakaran@kla-tencor.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
